default: true

# Rules to disable globally
MD013: false # line length
MD024: false # duplicate headings

# Rules to configure
MD003:
  style: 'atx' # Use # for headings
MD001: true # Heading levels should increment by one
MD031: true # Fenced code blocks should be surrounded by blank lines

ignore:
  - '.github/ISSUE_TEMPLATE/'
