# Location: /.pre-commit-config.yaml

repos:
  # Standard hooks for basic file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        # Exclude the dynamic.yml as it can be empty, causing syntax errors
        exclude: ^proxy/config/dynamic\.yml$
      - id: check-added-large-files

  # The primary code formatter for YAML and Markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [yaml, markdown]

  # A stricter linter for YAML best practices (beyond just formatting)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-c', '.yamllint.yml']