---
keys:
  - &admin_age age13kqew6kglat9hlswcstcxpdtvfh8v7pckr0wt3qvqkn7u2cj3e6qnm03uc
creation_rules:
  - path_regex: ^secrets/.*\.env\.encrypted$
    key_groups:
      - age:
          - *admin_age
