---
global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true

# EntryPoints are static definitions of network entry points into Traefik.
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
  matrix:
    address: ":8448"

# Providers instruct Traefik where to find routing configuration.
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

# The Certificate Resolvers are defined via command-line arguments in the
# docker-compose.yml file to allow for environment variable substitution.
