tunnel: 75ad59d3-5247-43f4-982a-48fe88c62247
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: ssh.wyattau.com
    service: ssh://127.0.0.1:2222
  - hostname: deploy.wyattau.com
    service: http://127.0.0.1:9001
  - service: http_status:404
