version: '3.8'

services:
  postgres-forgejo:
    image: postgres:${POSTGRES_FORGEJO_VERSION}
    container_name: operations-postgres-forgejo
    restart: unless-stopped
    volumes:
      - ${DATA_BASE_PATH}/operations/postgres-forgejo:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_FORGEJO}
      - POSTGRES_USER=${POSTGRES_USER_FORGEJO}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_FORGEJO}
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_FORGEJO} -d ${POSTGRES_DB_FORGEJO}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  forgejo:
    image: code.forgejo.org/forgejo/forgejo:${FORGEJO_VERSION}
    container_name: operations-forgejo
    restart: unless-stopped
    depends_on:
      postgres-forgejo:
        condition: service_healthy
    volumes:
      - ${DATA_BASE_PATH}/operations/forgejo:/data
    # user: "${PUID}:${PGID}"
    environment:
      - USER=git
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__service__SHOW_REGISTRATION_BUTTON=false
      - FORGEJO__metrics__ENABLED=true
      - FORGEJO__service__ENABLE_REVERSE_PROXY_AUTHENTICATION=true
      - FORGEJO__service__ENABLE_REVERSE_PROXY_AUTO_REGISTRATION=true
      - FORGEJO__service__REVERSE_PROXY_AUTHENTICATION_USER=X-Auth-Request-User
      - FORGEJO__service__REVERSE_PROXY_AUTHENTICATION_EMAIL=X-Auth-Request-Email
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=operations-postgres-forgejo:5432
      - FORGEJO__database__NAME=${POSTGRES_DB_FORGEJO}
      - FORGEJO__database__USER=${POSTGRES_USER_FORGEJO}
      - FORGEJO__database__PASSWD=${POSTGRES_PASSWORD_FORGEJO}
      - FORGEJO__server__DOMAIN=${FORGEJO_SUBDOMAIN}.${DOMAIN_NAME}
      - FORGEJO__server__ROOT_URL=https://${FORGEJO_SUBDOMAIN}.${DOMAIN_NAME}
      - FORGEJO__service__DISABLE_REGISTRATION=false
      - FORGEJO__container__ENABLE=true
      - FORGEJO__container__REGISTRY_HOST=${REGISTRY_SUBDOMAIN}.${DOMAIN_NAME}
      - FORGEJO__metrics__ENABLED=true
    networks:
      - traefik_net
      - backend_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"

      # --- 1. DEFINE A SINGLE SERVICE for the Forgejo container ---
      - "traefik.http.services.forgejo-svc.loadbalancer.server.port=3000"

      # --- 2. CONFIGURE THE ROUTER for the Forgejo Web UI ---
      - "traefik.http.routers.forgejo-web.rule=Host(`${FORGEJO_SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.forgejo-web.entrypoints=websecure"
      - "traefik.http.routers.forgejo-web.tls.certresolver=cloudflare"
      - "traefik.http.routers.forgejo-web.middlewares=keycloak-auth"
      - "traefik.http.routers.forgejo-web.service=forgejo-svc"

      # --- 3. CONFIGURE THE ROUTER for the Forgejo Container Registry ---
      - "traefik.http.routers.forgejo-registry.rule=Host(`${REGISTRY_SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.forgejo-registry.entrypoints=websecure"
      - "traefik.http.routers.forgejo-registry.tls.certresolver=cloudflare"
      - "traefik.http.routers.forgejo-registry.service=forgejo-svc"
    healthcheck:
      test: ["CMD-SHELL", "su-exec git /usr/local/bin/forgejo doctor check-database"]
      interval: 60s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.25'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  woodpecker-server:
    image: woodpeckerci/woodpecker-server:${WOODPECKER_SERVER_VERSION}
    container_name: operations-woodpecker-server
    restart: unless-stopped
    depends_on: [forgejo]
    volumes:
      - ${DATA_BASE_PATH}/operations/woodpecker:/var/lib/woodpecker/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WOODPECKER_HOST=https://${WOODPECKER_SUBDOMAIN}.${DOMAIN_NAME}
      - WOODPECKER_FORGEJO=true
      - WOODPECKER_FORGEJO_URL=https://${FORGEJO_SUBDOMAIN}.${DOMAIN_NAME}
      - WOODPECKER_FORGEJO_CLIENT=${WOODPECKER_FORGEJO_CLIENT_ID}
      - WOODPECKER_FORGEJO_SECRET=${WOODPECKER_FORGEJO_CLIENT_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_ADMINS=${WOODPECKER_ADMIN}
    networks:
      - traefik_net
      - backend_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.woodpecker.rule=Host(`${WOODPECKER_SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.woodpecker.entrypoints=websecure"
      - "traefik.http.services.woodpecker.loadbalancer.server.port=8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:${WOODPECKER_AGENT_VERSION}
    container_name: operations-woodpecker-agent
    restart: unless-stopped
    depends_on: [woodpecker-server]
    volumes: []
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WOODPECKER_SERVER=operations-woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_MAX_WORKFLOWS=2
      - WOODPECKER_BACKEND_DOCKER_PRIVILEGED_IMAGES=${WOODPECKER_DOCKER_PRIVILEGED_IMAGES}
    networks:
      - backend_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik_net:
    external: true
  backend_net:
    external: true
