services:
  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION}
    container_name: updater-watchtower
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: --interval 86400 --cleanup --label-enable --monitor-only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # shoutrrr format: ntfy://ntfy.sh/TOPIC?title=Watchtower
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=ntfy://${NTFY_URL}/${NTFY_TOPIC}?title=Watchtower+Update+Available
      - WATCHTOWER_LABEL_ENABLE=true
      - TZ=${TZ}
    networks: []
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 16M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
