services:
  watchtower:
    image: ghcr.io/wyattau/evergreen/watchtower:${WATCHTOWER_VERSION}
    container_name: updater-watchtower
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
    cap_drop:
    - ALL
    command: --interval 86400 --cleanup --label-enable --monitor-only
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - WATCHTOWER_NOTIFICATIONS=shoutrrr
    - WATCHTOWER_NOTIFICATION_URL=ntfy://${NTFY_URL}/${NTFY_TOPIC}?title=Watchtower+Update+Available
    - WATCHTOWER_LABEL_ENABLE=true
    - TZ=${TZ}
    networks: []
    deploy:
      resources:
        limits:
          memory: 64M
          pids: 100
        reservations:
          memory: 16M
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
