---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['monitoring-node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['monitoring-cadvisor:8080']
  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['proxy-traefik:8080']
  - job_name: 'forgejo'
    metrics_path: /metrics
    static_configs:
      - targets: ['operations-forgejo:3000']
  - job_name: 'keycloak'
    metrics_path: /metrics
    static_configs:
      - targets: ['iam-keycloak:8080']
