---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- datetime:
    text_size: x1
    format:
      dateStyle: short
      timeStyle: short

- search:
    provider: duckduckgo
    target: _blank
    showSearchSuggestions: true
    focus: true

- stocks:
    provider: finnhub
    color: true
    cache: 1
    watchlist:
      - GME
      - AMC
      - NVDA
      - AMD
      - TSM
      - MSFT
      - AAPL
      - BRK.A
