version: '3.8'

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: proxy-traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      # --- API and Dashboard ---
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # --- Log Settings ---
      - "--log.level=INFO"

      # --- Provider Settings ---
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_net"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      # --- Entrypoints ---
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.matrix.address=:8448"

      # --- Certificate Resolver (Let's Encrypt) ---
      - "--certificatesresolvers.cloudflare.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_BASE_PATH}/proxy/letsencrypt:/letsencrypt
      # Mount the single, self-contained configuration directory.
      # - ./traefik-config:/etc/traefik:ro
      - ./traefik-config/dynamic:/etc/traefik/dynamic:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.middlewares=keycloak-auth@file"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cloudflare-ddns:
    image: favonia/cloudflare-ddns:${CF_DDNS_VERSION}
    container_name: proxy-cloudflare-ddns
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - DOMAINS=${DOMAIN_NAME},traefik.${DOMAIN_NAME},auth.${DOMAIN_NAME},gitea.${DOMAIN_NAME},registry.${DOMAIN_NAME},taiga.${DOMAIN_NAME},grafana.${DOMAIN_NAME},prometheus.${DOMAIN_NAME},kuma.${DOMAIN_NAME},homepage.${DOMAIN_NAME},matrix.${DOMAIN_NAME},element.${DOMAIN_NAME},ocis.${DOMAIN_NAME}
      - IPV4_PROVIDER=all
      - PROXIED=true
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - "CRON=*/5 * * * *"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:${OAUTH2_PROXY_VERSION}
    container_name: proxy-oauth2-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # --- Core Configuration ---
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_UPSTREAMS=http://127.0.0.1 # Dummy upstream
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://auth.${DOMAIN_NAME}/realms/company-realm
      # --- OIDC Credentials ---
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      # --- Session Cookie Secret & Settings ---
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_COOKIE_SAMESITE=strict
      # --- This is the primary redirect URL for the proxy itself ---
      - OAUTH2_PROXY_REDIRECT_URL=https://traefik.${DOMAIN_NAME}/oauth2/callback
    networks:
      - traefik_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  well-known-server:
    image: nginx:${NGINX_VERSION}
    container_name: proxy-well-known-server
    restart: unless-stopped
    volumes:
      - ./traefik-config/dynamic/matrix-well-known.json:/usr/share/nginx/html/.well-known/matrix/server:ro
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matrix-well-known.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.matrix-well-known.entrypoints=websecure"
      - "traefik.http.middlewares.matrix-headers.headers.customresponseheaders.Content-Type=application/json; charset=utf-8"
      - "traefik.http.routers.matrix-well-known.middlewares=matrix-headers"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"

networks:
  traefik_net:
    external: true
