version: '3.8'

services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: proxy-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mount the real socket read-only
    environment:
      - LOG_LEVEL=info
      - CONTAINERS=1
      - NETWORKS=1
      - SERVICES=1
      - TASKS=1
      - NODES=1
      - POST=0
    networks:
      # This service is only visible on the backend network for security
      - backend_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: proxy-traefik
    restart: unless-stopped
    depends_on: [socket-proxy]
    security_opt:
      - no-new-privileges:true
    command:
      # - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://socket-proxy:2375"
      #- "--providers.file.directory=/etc/traefik/dynamic"
      #- "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.matrix.address=:8448"
      - "--certificatesresolvers.cloudflare.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
    labels:
      # --- Middleware: keycloak-auth (Moved from http.yml) ---
      - "traefik.http.middlewares.keycloak-auth.forwardauth.address=http://oauth2-proxy:4180"
      - "traefik.http.middlewares.keycloak-auth.forwardauth.authResponseHeaders=X-Auth-Request-Email,X-Auth-Request-User"
      - "traefik.http.middlewares.keycloak-auth.forwardauth.trustForwardHeader=true"

      # --- Router: traefik-dashboard ---
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=cloudflare"
      # --- Link Router to Middleware (Note: no '@file' suffix) ---
      - "traefik.http.routers.traefik-dashboard.middlewares=keycloak-auth"
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_BASE_PATH}/proxy/letsencrypt:/letsencrypt
      #- ./traefik-config/dynamic:/etc/traefik/dynamic:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLOUDFLARE_DNS_API_TOKEN=${CF_API_TOKEN}
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - traefik_net
      - backend_net
    # The dashboard router is defined exclusively in the dynamic http.yml file
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cloudflare-ddns:
    image: favonia/cloudflare-ddns:${CF_DDNS_VERSION}
    container_name: proxy-cloudflare-ddns
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - DOMAINS=${DOMAIN_NAME},traefik.${DOMAIN_NAME},auth.${DOMAIN_NAME},forgejo.${DOMAIN_NAME},registry-forgejo.${DOMAIN_NAME},taiga.${DOMAIN_NAME},grafana.${DOMAIN_NAME},prometheus.${DOMAIN_NAME},kuma.${DOMAIN_NAME},homepage.${DOMAIN_NAME},matrix.${DOMAIN_NAME},element.${DOMAIN_NAME},ocis.${DOMAIN_NAME},test.${DOMAIN_NAME}
      - IPV4_PROVIDER=all
      - PROXIED=true
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - "CRON=*/5 * * * *"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:${OAUTH2_PROXY_VERSION}
    container_name: proxy-oauth2-proxy
    restart: unless-stopped
    depends_on:
      - traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_net
      - backend_net # Connect oauth2-proxy to the backend network
    environment:
      # - OAUTH2_PROXY_LOG_LEVEL=debug
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_UPSTREAMS=static://200
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_WHITELIST_DOMAINS=.${DOMAIN_NAME}
      # --- OIDC Issuer URLs ---
      # Public URL for the user's browser
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://auth.${DOMAIN_NAME}/realms/company-realm
      # --- OIDC Credentials ---
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      # --- Session Cookie Secret & Settings ---
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_COOKIE_SAMESITE=strict
      - OAUTH2_PROXY_COOKIE_DOMAIN=.${DOMAIN_NAME}
      #- OAUTH2_PROXY_REDIRECT_URL=https://traefik.${DOMAIN_NAME}/oauth2/callback
      # This bypasses the public DNS lookup for server-to-server communication.
      #- OAUTH2_PROXY_LOGIN_URL=https://auth.${DOMAIN_NAME}/realms/company-realm/protocol/openid-connect/auth
      - OAUTH2_PROXY_REDEEM_URL=http://iam-keycloak:8080/realms/company-realm/protocol/openid-connect/token
      - OAUTH2_PROXY_OIDC_JWKS_URL=http://iam-keycloak:8080/realms/company-realm/protocol/openid-connect/certs
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.oauth2-proxy.rule=(Host(`forgejo.${DOMAIN_NAME}`) || Host(`traefik.${DOMAIN_NAME}`)) && PathPrefix(`/oauth2`)"
      #- "traefik.http.routers.oauth2-proxy.rule=HostRegexp(`{host:.+}`) && PathPrefix(`/oauth2`)"
      - "traefik.http.routers.oauth2-proxy.entrypoints=websecure"
      - "traefik.http.routers.oauth2-proxy.tls.certresolver=cloudflare"
      - "traefik.http.services.oauth2-proxy.loadbalancer.server.port=4180"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  well-known-server:
    image: nginx:${NGINX_VERSION}
    container_name: proxy-well-known-server
    restart: unless-stopped
    volumes:
      - ./traefik-config/dynamic/matrix-well-known.json:/usr/share/nginx/html/.well-known/matrix/server:ro
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.matrix-well-known.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.matrix-well-known.entrypoints=websecure"
      - "traefik.http.middlewares.matrix-headers.headers.customresponseheaders.Content-Type=application/json; charset=utf-8"
      - "traefik.http.routers.matrix-well-known.middlewares=matrix-headers"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"

networks:
  traefik_net:
    external: true
  backend_net:
    external: true
