---
- Admin:
    - Cloudflare:
        - icon: cloudflare.svg
          href: https://dash.cloudflare.com/
    - GitHub:
        - icon: github.svg
          href: https://github.com/
    - TrueNAS:
        - icon: truenas.webp
          href: https://truenas.wyattau.com
    - Grafana:
        - icon: grafana.webp
          href: https://grafana.wyattau.com

- Developer:
    - Stack Overflow:
        - icon: stackoverflow.svg
          href: https://stackoverflow.com/
    - DevDocs:
        - icon: devdocs.svg
          href: https://devdocs.io/
    - Docker Hub:
        - icon: docker.webp
          href: https://hub.docker.com/
    - GitHub Docs:
        - icon: github.svg
          href: https://docs.github.com/

- Media:
    - YouTube:
        - icon: youtube.svg
          href: https://youtube.com/
    - Spotify:
        - icon: spotify.svg
          href: https://open.spotify.com/
    - Reddit:
        - icon: reddit.svg
          href: https://reddit.com/
    - Hacker News:
        - icon: ycombinator.svg
          href: https://news.ycombinator.com/
