version: '3.8'

services:
  postgres-iam:
    image: postgres:${POSTGRES_VERSION}
    container_name: iam-postgres
    restart: unless-stopped
    volumes:
      - ${DATA_BASE_PATH}/iam/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: iam-keycloak
    restart: unless-stopped
    command: start
    depends_on:
      postgres-iam:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=iam-postgres
      - KC_DB_URL_DATABASE=${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_PROXY=edge
      - KC_HOSTNAME=${KEYCLOAK_SUBDOMAIN}.${DOMAIN_NAME}
      - KC_HTTP_RELATIVE_PATH=/
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    networks:
      - traefik_net
      - backend_net
    # Service discovery is handled manually by the file provider in the proxy stack. As docker does not correctly manage multi stack enviroment.
    healthcheck:
      test: >
        [ -f /tmp/HealthCheck.java ] || echo 'public class HealthCheck { public static void main(String[] args) throws java.io.IOException { try { java.net.URI uri = java.net.URI.create(args[0]); java.net.HttpURLConnection con = (java.net.HttpURLConnection) uri.toURL().openConnection(); con.setRequestMethod("GET"); con.setConnectTimeout(1000); con.setReadTimeout(1000); System.exit(con.getResponseCode() == 200 ? 0 : 1); } catch (Exception e) { System.exit(1); } } }' > /tmp/HealthCheck.java;
        java /tmp/HealthCheck.java http://localhost:8080/health/ready
      interval: 15s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik_net:
    external: true
  backend_net:
    external: true
