version: '3.8'

services:
  postgres-iam:
    image: postgres:${POSTGRES_VERSION}
    container_name: iam-postgres
    restart: unless-stopped
    volumes:
      - ${DATA_BASE_PATH}/iam/postgres:/var/lib/postgresql/data
    environment:
      # Bitnami Keycloak expects these specific variable names for its database
      - POSTGRES_DB=${KEYCLOAK_DATABASE_NAME}
      - POSTGRES_USER=${KEYCLOAK_DATABASE_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DATABASE_USER} -d ${KEYCLOAK_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: iam-keycloak
    restart: unless-stopped
    command: start --optimized --hostname-strict=false
    depends_on:
      postgres-iam:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      # Database Connection
      - KC_DB=postgres
      - KC_DB_URL_HOST=iam-postgres
      - KC_DB_URL_DATABASE=${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      # Proxy and Hostname Configuration
      - KC_PROXY=edge
      - KC_HOSTNAME=auth.${DOMAIN_NAME}
      - KC_HOSTNAME_URL=https://auth.${DOMAIN_NAME}
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_RELATIVE_PATH=/
      - KC_HEALTH_ENABLED=true
    networks:
      - traefik_net
      - backend_net
    healthcheck:
      test: ['CMD', '/usr/bin/curl', '-f', 'http://localhost:8080/health/ready']
      interval: 15s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik_net:
    external: true
  backend_net:
    external: true
