# ===================================================================
# DYNAMIC ROUTER & SERVICE CONFIGURATION (MANUAL DISCOVERY)
# ===================================================================

http:
  routers:
    keycloak-router:
      rule: "Host(`auth.wyattau.com`)"
      entryPoints:
        - websecure
      service: "keycloak-service"
      tls:
        certResolver: cloudflare

  services:
    keycloak-service:
      loadBalancer:
        servers:
          # This uses Docker's internal DNS to resolve the container name.
          # This is the most reliable method.
          - url: "http://iam-keycloak:8080"
