# Path: /proxy/traefik-config/dynamic/http.yml
# ===================================================================
# CONSOLIDATED DYNAMIC HTTP CONFIGURATION
# ===================================================================

http:
  # --- MIDDLEWARES ---
  middlewares:
    securityHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    keycloak-auth:
      forwardAuth:
        address: "http://oauth2-proxy:4180"
        authResponseHeaders:
          - "X-Auth-Request-Email"
          - "X-Auth-Request-User"
        trustForwardHeader: true

  # --- ROUTERS ---
  #routers:
  #  traefik-dashboard:
  #    rule: "Host(`traefik.wyattau.com`)"
  #    entryPoints:
  #      - websecure
  #    service: "api@internal"
  #    middlewares:
  #      - keycloak-auth
  #    tls:
  #      certResolver: cloudflare

  #  keycloak-router:
  #    rule: "Host(`auth.wyattau.com`)"
  #    entryPoints:
  #      - websecure
  #    service: "keycloak-service"
  #    tls:
  #      certResolver: cloudflare
#
  ## --- SERVICES ---
  #services:
  #  keycloak-service:
  #    loadBalancer:
  #      servers:
  #        - url: "http://iam-keycloak:8080"
  #      passHostHeader: true
