# Path: /proxy/traefik-config/dynamic/middlewares.yml
http:
  middlewares:
    securityHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    keycloak-auth:
      forwardAuth:
        # The address now points to the new oauth2-proxy service and its port.
        address: "http://proxy-oauth2-proxy:4180"
        authResponseHeaders:
          - "X-Auth-Request-Email"
          - "X-Auth-Request-User"
        trustForwardHeader: true
