#!/usr/bin/env python3
"""Generate Promtail config with per-container labels from Docker.

Promtail 3.6.x Docker SD fails on IPv6 CIDR addresses (known bug):
  ParseAddr("fdd0:0:0:13::1/64"): unexpected character, want colon (at "/64")

This script generates a static config that reads Docker JSON log files directly,
bypassing Docker SD entirely. Each container gets proper job/container/stack labels
derived from Docker Compose labels.

Usage:
  sudo python3 generate_config.py

Requirements:
  - Docker CLI access (via socket or TCP)
  - Read access to Docker log directory (/mnt/.ix-apps/docker/containers/)
  - Write access to output path (default: ./config.yml)
"""

import subprocess
import os
import sys

# Configuration
DOCKER_LOG_DIR = "/mnt/.ix-apps/docker/containers"
OUTPUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.yml")
VICTORIALOGS_URL = "http://monitoring-victorialogs:9428/insert/loki/api/v1/push"
LOG_PATH_PREFIX = "/docker-logs"


def get_containers():
    """Get running containers with full IDs, names, and compose labels."""
    result = subprocess.run(
        [
            "docker", "ps", "--no-trunc", "--format",
            "{{.ID}} {{.Names}} {{.Label \"com.docker.compose.service\"}} "
            "{{.Label \"com.docker.compose.project\"}}"
        ],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print("ERROR: docker ps failed: " + result.stderr, file=sys.stderr)
        sys.exit(1)

    containers = []
    for line in result.stdout.strip().split("\n"):
        if not line.strip():
            continue
        parts = line.split()
        full_id = parts[0]
        name = parts[1]
        service = parts[2] if len(parts) > 2 and parts[2] else name.rsplit("-", 1)[-1]
        project = parts[3] if len(parts) > 3 and parts[3] else "standalone"
        containers.append({
            "id": full_id,
            "name": name,
            "service": service,
            "project": project,
        })
    return containers


def generate_config(containers):
    """Generate Promtail YAML config with per-container static_configs."""
    lines = [
        "---",
        "# NOTE: Auto-generated by generate_config.py.",
        "# Do not edit manually. Run: sudo python3 generate_config.py",
        "#",
        "# File-based log collection instead of Docker SD.",
        "# Promtail 3.6.x has a bug where Docker SD fails with:",
        '#   ParseAddr("fdd0:0:0:13::1/64"): unexpected character, want colon (at "/64")',
        "# Docker returns IPv6 CIDR addresses that Promtail's Go net library cannot parse.",
        "# This config reads Docker's JSON log files directly, bypassing Docker SD entirely.",
        "# The Docker containers directory is mounted at /docker-logs inside the container.",
        "",
        "server:",
        "  http_listen_port: 9080",
        "  grpc_listen_port: 0",
        "",
        "positions:",
        "  filename: /tmp/positions.yaml",
        "",
        "clients:",
        "  - url: " + VICTORIALOGS_URL,
        "",
        "scrape_configs:",
        "  - job_name: containers",
        "    static_configs:",
    ]

    count = 0
    missing = 0
    for c in containers:
        log_dir = os.path.join(DOCKER_LOG_DIR, c["id"])
        log_file = os.path.join(log_dir, c["id"] + "-json.log")

        if os.path.isdir(log_dir):
            lines.append("      - targets:")
            lines.append("          - localhost")
            lines.append("        labels:")
            lines.append('          job: "' + c["service"] + '"')
            lines.append('          container: "' + c["name"] + '"')
            lines.append('          stack: "' + c["project"] + '"')
            lines.append("          __path__: " + LOG_PATH_PREFIX + "/" + c["id"] + "/" + c["id"] + "-json.log")
            count += 1
        else:
            missing += 1
            print("WARN: No log directory for " + c["name"] + " (" + c["id"][:12] + ")", file=sys.stderr)

    # Pipeline stages: docker stage parses Docker JSON log format,
    # timestamp stage extracts time from Docker's log timestamp field.
    # NOTE: timestamp sub-keys MUST use inline dict syntax to avoid YAML
    # parsing ambiguity where "source:" and "format:" are interpreted as
    # sibling keys of "timestamp:" instead of child keys.
    lines.extend([
        "",
        "    pipeline_stages:",
        "      - docker: {}",
        "      - timestamp: {source: time, format: RFC3339Nano}",
        "",
    ])

    return "\n".join(lines), count, missing


def main():
    containers = get_containers()
    print("Found " + str(len(containers)) + " running containers")

    config, count, missing = generate_config(containers)
    print("Generated config with " + str(count) + " log targets, " + str(missing) + " missing")

    with open(OUTPUT_PATH, "w") as f:
        f.write(config)
    print("Written to " + OUTPUT_PATH)


if __name__ == "__main__":
    main()
