apiVersion: 1
policies:
  - orgId: 1
    name: default_critical
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: ntfy
        matchers:
          - severity =~ "critical"
  - orgId: 1
    name: default_warning
    group_by: ['alertname']
    group_wait: 5m
    group_interval: 30m
    repeat_interval: 12h
    routes:
      - receiver: ntfy
        matchers:
          - severity =~ "warning"
  - orgId: 1
    # Catch-all for alerts with no severity label
    name: default
    group_by: ['alertname']
    group_wait: 5m
    group_interval: 30m
    repeat_interval: 12h
    routes:
      - receiver: ntfy
