apiVersion: 1
policies:
  - orgId: 1
    receiver: ntfy-warning
    group_by: ['alertname']
    group_wait: 5m
    group_interval: 5m
    repeat_interval: 12h
    routes:
      - receiver: ntfy-critical
        matchers:
          - severity =~ "critical"
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        continue: false
      - receiver: ntfy-warning
        matchers:
          - severity =~ "warning|info"
        group_wait: 5m
        repeat_interval: 12h
        continue: false
