apiVersion: 1
templates:
  - orgId: 1
    name: default
    template: |
      {{ define "default_title" }}[{{ .GroupLabels.alertname }}] {{ .CommonLabels.alertname }}
      {{ end }}
      {{ define "default_message" }}{{ range .Alerts }}Alert: {{ .Labels.alertname }}
      Severity: {{ .Labels.severity }}
      Container: {{ .Labels.container }}
      Value: {{ .Value }}
      StartsAt: {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}
      {{ end }}
      {{ end }}
