---
# defaults file for manage_runners
forgejo_runner_base_path: /opt/forgejo-runners
forgejo_runner_daemon_image: ghcr.io/wyattau/runner-images/runner-daemon:2.0.0
forgejo_runner_work_image: ghcr.io/wyattau/runner-images/node:1.0.0
forgejo_runner_user_uid: 65532
forgejo_runner_docker_gid: 956

forgejo_runner_forgejo_url: http://192.168.1.3:3000

forgejo_runner_capacity: 4
forgejo_runner_timeout: 3h0m0s
forgejo_runner_update_timeout: 1h0m0s
forgejo_runner_log_level: info

forgejo_runner_runners:
  - name: general
    labels:
      ubuntu-latest: docker://ghcr.io/wyattau/runner-images/ubuntu:24.04
      ubuntu-22.04: docker://ghcr.io/wyattau/runner-images/ubuntu:22.04
      node: docker://ghcr.io/wyattau/runner-images/node:1.0.0
    capacity: 4

  - name: peptide-web
    labels:
      ubuntu-latest: docker://ghcr.io/wyattau/runner-images/ubuntu:24.04
      node: docker://ghcr.io/wyattau/runner-images/node:1.0.0
      docker: docker://catthehacker/ubuntu:act-latest
    capacity: 4

  - name: questhive
    labels:
      ubuntu-latest: docker://ghcr.io/wyattau/runner-images/ubuntu:24.04
      node: docker://ghcr.io/wyattau/runner-images/node:1.0.0
    capacity: 4
