---
name: CI Configuration Validation

# yamllint disable-line rule:truthy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate-and-lint:
    name: Validate, Lint, and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks on all files
        # This command runs the exact same checks defined in .pre-commit-config.yaml
        # ensuring consistency between local development and CI.
        run: pre-commit run --all-files

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Aggregate .env.example Files for Validation
        run: |
          echo "Preparing a unified .env file for validation..."
          find . -name '.env.example' -exec cat {} + | sort -u > .env
          echo "AUTHENTIK_OUTPOST_TOKEN=placeholder_for_ci_check" >> .env

      - name: Validate All Docker Compose Files
        run: |
          for dir in $(find . -name 'docker-compose.yml' -exec dirname {} \;); do
            echo "Validating Docker Compose in directory: $dir"
            docker-compose -f "$dir/docker-compose.yml" --env-file ./.env config > /dev/null
            if [ $? -ne 0 ]; then
              echo "::error::Validation failed for Docker Compose file in $dir"
              exit 1
            fi
            echo "Validation successful for $dir"
          done

      - name: All Checks Passed
        run: echo "All infrastructure configuration files are valid and correctly formatted."

  deploy-to-machines:
    name: Deploy to All Machines
    runs-on: ubuntu-latest
    needs: validate-and-lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    strategy:
      # These MUST correspond to the suffix of the secret names.
      matrix:
        machine: ['TRUENAS']
        # To add a new machine, just add its identifier here (e.g., 'MACHINE_D')
        # and create a corresponding secret named 'STACK_WEBHOOK_MACHINE_D'.

    steps:
      - name: Trigger deployment for ${{ matrix.machine }}
        # This step dynamically builds the secret name based on the matrix identifier.
        # For example, when matrix.machine is 'TRUENAS', it looks for secrets.STACK_WEBHOOK_TRUENAS.
        env:
          # Create an environment variable that holds the correct secret for this run.
          PORTAINER_WEBHOOK_URL: ${{ secrets[format('STACK_WEBHOOK_{0}', matrix.machine)] }}

        # We add a condition to ensure the curl command doesn't run with an empty URL
        # if a secret for a machine is accidentally missing.
        if: env.PORTAINER_WEBHOOK_URL != ''

        # The curl command now uses the environment variable.
        run: |
          echo "Triggering webhook for ${{ matrix.machine }}..."
          curl -s -X POST "$PORTAINER_WEBHOOK_URL"
